version: "3"
services:
  clickhouse-server:
    image: "yandex/clickhouse-server"
    volumes:
      - ./clickhouse_configs/users.d:/etc/clickhouse-server/users.d
    container_name: "test-clickhouse-server"
    ports:
        - 8123:8123
    ulimits: 
      nofile:
        soft: 262144
        hard: 262144      